const actionTypes = {
	ADD_ORDER: 'ADD_ORDER',
	EDIT_ORDER: 'EDIT_ORDER',
	DELETE_ORDER: 'DELETE_ORDER',
	SET_DISPLAY_FILTER: 'SET_DISPLAY_FILTER',
	TOGGLE_COMPLETED: 'TOGGLE_COMPLETED'
}

export default actionTypes;

